### ISSUE TITLE
"set-env" command is deprecated 

### ISSUE THREAD

**Issue by aa2kb** [allenevans/set-env#12]
Getting error

Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by allenevans** [comment]
Please could you try v2.0.0.

**Comment by aa2kb** [comment]
Okay Thanks 
it works
