### ISSUE TITLE
Enable overwriting by default

### ISSUE THREAD

**Issue by clabe45** [allenevans/set-env#2]
I suggest environment variables to be overwritten by default, because when you set an environment variable in the terminal, it overwrites any existing value. I think `overwrite` either shouldn't be an option or should be disabled by default.

I am willing to contribute to make this change if it is to implemented!

**Comment by allenevans** [comment]
You make a very good point. I've put together PR https://github.com/allenevans/set-env/pull/3 to change the default behaviour. I'll give it a test first in some of my build pipelines.

For now I'll leave `overwrite` as an option but consider it for deprecation in future versions.
