### ISSUE TITLE
Using deprecated node version

### ISSUE THREAD

**Issue by chowda-pki** [allenevans/set-env#22]
**Warning:**
The following actions uses node12 which is deprecated and will be forced to run on node16: allenevans/set-env@v2.0.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by allenevans** [comment]
Please use version 3.0.0

**Comment by BTOdell** [comment]
Version 3.0.0 was never published or marked as a release, so it can't be used in workflows at the moment.
